/**
 * OpenClaw compatibility names for the Host-neutral private authority store.
 * New core code must import semantic-private-authority-offers directly.
 */
export {
  SEMANTIC_APPROVAL_AUTHORITY_KIND as OPENCLAW_APPROVAL_AUTHORITY_KIND,
  SEMANTIC_INTERACTION_AUTHORITY_KIND as OPENCLAW_INTERACTION_AUTHORITY_KIND,
  SEMANTIC_INTERACTION_AUTHORITY_SUBJECT_KINDS as OPENCLAW_INTERACTION_AUTHORITY_SUBJECT_KINDS,
  SEMANTIC_PRIVATE_AUTHORITY_OFFER_LIMIT as OPENCLAW_PRIVATE_AUTHORITY_OFFER_LIMIT,
  SEMANTIC_PRIVATE_AUTHORITY_OFFER_TTL_MS as OPENCLAW_PRIVATE_AUTHORITY_OFFER_TTL_MS,
  consumeSemanticPrivateAuthorityOffer as consumeOpenClawPrivateAuthorityOffer,
  invalidateSemanticInteractionAuthorityOffersForSubject as invalidateOpenClawInteractionAuthorityOffersForSubject,
  peekSemanticPrivateAuthorityOffer as peekOpenClawPrivateAuthorityOffer,
  rememberSemanticPrivateAuthorityOffer as rememberOpenClawPrivateAuthorityOffer,
  semanticApprovalAuthorityOfferKey as openClawApprovalAuthorityOfferKey,
  semanticInteractionAuthorityOfferKey as openClawInteractionAuthorityOfferKey,
  semanticManagedTurnInteractionAuthorityOfferKey as openClawManagedTurnInteractionAuthorityOfferKey,
  semanticTerminalWatchInteractionAuthorityOfferKey as openClawTerminalWatchInteractionAuthorityOfferKey
} from "./semantic-private-authority-offers.js";
export type {
  SemanticInteractionAuthoritySubjectKind as OpenClawInteractionAuthoritySubjectKind,
  SemanticPrivateAuthorityOfferKey as OpenClawPrivateAuthorityOfferKey,
  SemanticPrivateAuthorityOfferPayload as OpenClawPrivateAuthorityOfferPayload,
  SemanticPrivateAuthorityTarget as OpenClawPrivateAuthorityTarget
} from "./semantic-private-authority-offers.js";
